[package]
name = "lunch-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
daemonize = "0.5.0"
dotenv = "0.15.0"
rand = "0.8.5"
reqwest = { version = "0.12.12", features = ["blocking"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
